<div class="jumbotron">
<?php

if (!$this->identity()) {
?>
    <a class="btn btn-large btn-primary"
    href="<?= $this->url('zf-oauth2-client', array('profile' => 'default')); ?>">
        OAuth2 Login
    </a>
<?php
} else {
?>
<h3>OAuth2 Authenticated User</h3>
<pre>
<?php print_r($this->identity()); ?>
</pre>
    <a class="btn btn-primary" href="<?= $this->url('logout'); ?>">Logout</a>
<?php
}
?>
</div>
